version: '3.5'
services:
  nginx-proxy:
    build: ./nginx
    image: nginx-proxy:latest
    hostname: nginx-proxy
    container_name: nginx-proxy
    networks:
      - nuts
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./data/nginx-proxy.log/:/var/log/nginx/
    restart: always
    ports:
      - 9100:9100
#      - 9101:9101
    depends_on:
       - node-exporter
#        - cadvisor

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    networks:
      - nuts
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
#     ports:
#       - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/devicemapper|rootfs/var/lib/docker/aufs)($$|/)'

#   cadvisor:
#     image: google/cadvisor
#     container_name: cadvisor
#     networks:
#       - nuts
#     restart: always
#     logging:
#       driver: "json-file"
#       options:
#         max-size: "10m"
#         max-file: "5"
#     ports:
#       - 9101:8080
#     volumes:
#       - /:/rootfs:ro
#       - /var/run:/var/run:rw
#       - /sys:/sys:ro
#       - /var/lib/docker/:/var/lib/docker:ro
networks:
  nuts:
    driver: bridge      