version: '3.7'

services:
  pr-nginx-proxy:
    build: ./nginx
    image: pr-nginx-proxy:latest
    hostname: pr-nginx-proxy
    container_name: pr-nginx-proxy
    networks:
      - nuts
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./data/nginx-proxy.log/:/var/log/nginx/
    restart: always
    ports:
      - 9090:9090
      - 3000:3000
    depends_on:
       - prometheus
       - grafana


  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.1.0
    networks:
      - nuts
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      #- ./data/prometheus_data:/prometheus/data
     # - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
#     ports:
#       - '9090:9090'

  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - nuts
    restart: always
    volumes:
      - ./data/grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ORG_ROLE=viewer
      #- GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
#     ports:
#       - '3000:3000'
networks:
  nuts:
    driver: bridge 

